name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    name: checkout-repository
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev
        uses: actions/checkout@v4
      - name: set up Java21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: fetch Maven dependancies
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependancies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/**/pom.xml') }}
          restore-keys: | # In case my key's lost, I got my own back
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: run Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
