name: Bonjour

on: [push] # Ce workflow se déclenche sur un push dans le dépôt

jobs:
  Salutations: # Nom de job: Salutations
    name: Salutations
    runs-on: ubuntu-latest # OS qui lance le workflow
    steps:
      - name: Hello # Tâche
        env:
          personneASaluer: 'Mon voisin Totoro'
        run: echo "Bonjour ${personneASaluer}"
      - name: L'heure de salutation
        run: echo "L'heure était $(date)."

